{
 "title": "Systems stats time lag comparison",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics WHERE metric LIKE 'psutil%' ORDER BY 1;"
   },
   { "name": "agg_interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" },
   { "name": "lag_interval", "query": "1h,6h,12h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'cpu_utilization')::float8) \"CPU utilization\"\nFROM\n  psutil_cpu\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg(cpu_utilization) \"CPU utilization-$lag_interval\"\nFROM (\nSELECT\n  time + '$lag_interval'::interval as time,\n  (data->'cpu_utilization')::float8 as cpu_utilization\nFROM\n  psutil_cpu\nWHERE\n  dbname = '$dbname'\n  and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n) x\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "IO Wait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'iowait')::float8) as \"IOWait\"\nFROM\n  psutil_cpu\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg(iowait) \"IOWait-$lag_interval\"\nFROM (\nSELECT\n  time + '$lag_interval'::interval as time,\n  (data->'iowait')::float8 as iowait\nFROM\n  psutil_cpu\nWHERE\n  dbname = '$dbname'\n  and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n) x\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Memory used (%)",
   "type": "graph",
   "description": "(total - available) /  total * 100",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'percent')::float8) as \"Mem. used\"\nFROM\n  psutil_mem\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg(used) \"Mem. used-$lag_interval\"\nFROM (\nSELECT\n  time + '$lag_interval'::interval as time,\n  (data->'percent')::float8 as used\nFROM\n  psutil_mem\nWHERE\n  dbname = '$dbname'\n  and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n) x\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'available')::float8) as \"Mem. available\"\nFROM\n  psutil_mem\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg(available) \"Mem. available-$lag_interval\"\nFROM (\nSELECT\n  time + '$lag_interval'::interval as time,\n  (data->'available')::float8 as available\nFROM\n  psutil_mem\nWHERE\n  dbname = '$dbname'\n  and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n) x\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Swap used (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'swap_percent')::float8) as \"Swap used\"\nFROM\n  psutil_mem\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg(swap_percent) \"Swap used-$lag_interval\"\nFROM (\nSELECT\n  time + '$lag_interval'::interval as time,\n  (data->'swap_percent')::float8 as swap_percent\nFROM\n  psutil_mem\nWHERE\n  dbname = '$dbname'\n  and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n) x\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Total bytes read per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((read_bytes_lag - read_bytes) / extract(epoch from time_lag - time))::int8 as \"read_bytes_s\"\nFROM (\n  SELECT\n    time,\n    lag(time) over w as time_lag,\n    (data->'read_bytes')::int8 as read_bytes,\n    lag((data->'read_bytes')::int8) over w as read_bytes_lag\n  FROM\n    psutil_disk_io_total\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n  WINDOW w AS (ORDER BY time)\n) x\nWHERE read_bytes >= read_bytes_lag and time > time_lag\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((read_bytes_lag - read_bytes) / extract(epoch from time_lag - time))::int8 as \"read_bytes_s-$lag_interval\"\nFROM (\n  SELECT\n    time + '$lag_interval'::interval as time,\n    lag(time) over w + '$lag_interval'::interval as time_lag,\n    (data->'read_bytes')::int8 as read_bytes,\n    lag((data->'read_bytes')::int8) over w as read_bytes_lag\n  FROM\n    psutil_disk_io_total\n  WHERE\n    time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n    AND dbname = '$dbname'\n  WINDOW w AS (ORDER BY time)\n) x\nWHERE read_bytes >= read_bytes_lag and time > time_lag\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Total bytes written per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((write_bytes_lag - write_bytes) / extract(epoch from time_lag - time))::int8 as \"write_bytes_s\"\nFROM (\n  SELECT\n    time,\n    lag(time) over w as time_lag,\n    (data->'write_bytes')::int8 as write_bytes,\n    lag((data->'write_bytes')::int8) over w as write_bytes_lag\n  FROM\n    psutil_disk_io_total\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n  WINDOW w AS (ORDER BY time)\n) x\nWHERE write_bytes >= write_bytes_lag and time > time_lag\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((write_bytes_lag - write_bytes) / extract(epoch from time_lag - time))::int8 as \"write_bytes_s-$lag_interval\"\nFROM (\n  SELECT\n    time + '$lag_interval'::interval as time,\n    lag(time) over w + '$lag_interval'::interval as time_lag,\n    (data->'write_bytes')::int8 as write_bytes,\n    lag((data->'write_bytes')::int8) over w as write_bytes_lag\n  FROM\n    psutil_disk_io_total\n  WHERE\n    time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n    AND dbname = '$dbname'\n  WINDOW w AS (ORDER BY time)\n) x\nWHERE write_bytes >= write_bytes_lag and time > time_lag\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  }
 ]
}