{
 "title": "Tables top",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbname", "query": { "query": "label_values(dbname)" } },
   { "name": "top", "query": "1,3,5,10,20" }
  ]
 },
 "panels": [
  {
   "title": "Total relation size",
   "type": "table",
   "description": "i.e. including indexes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(topk($top, pgwatch2_table_stats_total_relation_size_b{dbname=\"$dbname\"})) by (table_full_name)"
    }
   ]
  },
  {
   "title": "Table data size",
   "type": "table",
   "description": "i.e. excluding indexes, but including TOAST + VM + FSM",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(topk($top, pgwatch2_table_stats_table_size_b{dbname=\"$dbname\"})) by (table_full_name)"
    }
   ]
  },
  {
   "title": "Total growth",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(topk($top, delta(pgwatch2_table_stats_total_relation_size_b{dbname=\"$dbname\"}[365d]))) by (table_full_name)"
    }
   ]
  },
  {
   "title": "Seq. scans (>100MB)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($top, sum(increase(pgwatch2_table_stats_seq_scan{dbname=\"$dbname\",table_size_cardinality_mb=~\"3|4|5|6|7|8|9\"}[$__range])) by (table_full_name))"
    }
   ]
  },
  {
   "title": "Block read bandwith",
   "type": "table",
   "description": "Blocks read from file system. NB! Note that some of those reads come from the kernel buffercache still",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "8192 * topk($top, sum(increase(pgwatch2_table_io_stats_heap_blks_read{dbname=\"$dbname\"}[$__range]) + increase(pgwatch2_table_io_stats_idx_blks_read{dbname=\"$dbname\"}[$__range])) by (table_full_name))"
    }
   ]
  },
  {
   "title": "INSERT",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($top, sum(increase(pgwatch2_table_stats_n_tup_ins{dbname=\"$dbname\"}[$__range])) by (table_full_name))"
    }
   ]
  },
  {
   "title": "UPDATE",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($top, sum(increase(pgwatch2_table_stats_n_tup_upd{dbname=\"$dbname\"}[$__range])) by (table_full_name))"
    }
   ]
  },
  {
   "title": "DELETE",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($top, sum(increase(pgwatch2_table_stats_n_tup_del{dbname=\"$dbname\"}[$__range])) by (table_full_name))"
    }
   ]
  }
 ]
}