{
 "title": "Table details",
 "tags": [ "pgwatch2" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES FROM \"table_stats\" WITH KEY = \"dbname\""
   },
   {
    "name": "table_full_name",
    "query": "SHOW TAG VALUES FROM \"table_stats\" WITH KEY = \"table_full_name\" WHERE dbname = '$dbname'"
   }
  ]
 },
 "panels": [
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total_relation_size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "SELECT mean(\"total_relation_size_b\") FROM \"table_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "total_relation_size_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    },
    {
     "alias": "table_size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "SELECT mean(\"total_relation_size_b\") FROM \"table_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "table_size_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    },
    {
     "alias": "index_size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "index_stats",
     "query": "SELECT mean(\"total_relation_size_b\") FROM \"table_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "index_size_b" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    },
    {
     "alias": "toast_size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "SELECT mean(\"total_relation_size_b\") FROM \"table_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "toast_size_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Scans (1m rate log.)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "seq_scans",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "select": [
      [
       { "params": [ "seq_scan" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    },
    {
     "alias": "idx_scans",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "SELECT non_negative_derivative(mean(\"idx_scan\"), 1m) FROM \"table_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "idx_scan" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "IUD (1m rate log.)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "INS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "select": [
      [
       { "params": [ "n_tup_ins" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    },
    {
     "alias": "UPD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "select": [
      [
       { "params": [ "n_tup_upd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    },
    {
     "alias": "HOT_UPD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "select": [
      [
       { "params": [ "n_tup_hot_upd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    },
    {
     "alias": "DEL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "select": [
      [
       { "params": [ "n_tup_del" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers hit rates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Heap",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_io_stats",
     "query": "SELECT non_negative_derivative(mean(\"heap_blks_hit\"), 10s) /  (non_negative_derivative(mean(\"heap_blks_hit\"), 10s) + non_negative_derivative(mean(\"heap_blks_read\"), 10s)) * 100 FROM \"table_io_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "heap_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    },
    {
     "alias": "Indexes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_io_stats",
     "query": "SELECT non_negative_derivative(mean(\"idx_blks_hit\"), 10s) /  (non_negative_derivative(mean(\"idx_blks_hit\"), 10s) + non_negative_derivative(mean(\"idx_blks_read\"), 10s)) * 100 FROM \"table_io_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "heap_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Scans per index (1m rate log.)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_index_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "index_stats",
     "select": [
      [
       { "params": [ "idx_scan" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2017/11/CYBERTEC-LOGO-GREY-BLUE-SVG.svg\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}