{
 "title": "System Stats",
 "description": "Needs according psutil_* helper stored procedures installed on monitored Postgres DBs",
 "tags": [ "pgwatch2" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics WHERE metric LIKE 'psutil%' ORDER BY 1;"
   },
   { "name": "agg_interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "System load ($agg_interval avg.)",
   "type": "graph",
   "description": "a.k.a. CPU run  queue length or Load Average, reported e.g. by the \"uptime\" command",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "normalized to #CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "psutil_cpu",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'load_1m_norm')::float8) \"normalized to #CPU\",\n  avg((data->'load_1m')::float8) \"as reported by /proc/loadavg\"\nFROM\n  psutil_cpu\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU utilization % ($agg_interval avg.)",
   "type": "graph",
   "description": "System-wide CPU utilization as reported by psutil.cpu_percent()",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "psutil_cpu",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'cpu_utilization')::float8) \"utilization\"\nFROM\n  psutil_cpu\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage distribution ($agg_interval avg.)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "psutil_cpu",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'idle')::float8) as \"idle\",\n  avg((data->'user')::float8) as \"user\",\n  avg((data->'system')::float8) as \"system\",\n  avg((data->'iowait')::float8) as \"iowait\",\n  avg((data->'other')::float8) as \"other\",\n  avg((data->'irqs')::float8) as \"irqs\"\nFROM\n  psutil_cpu\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage ($agg_interval avg.)",
   "type": "graph",
   "description": "NB! Doesn't have to necessarily equal 100%  to values reported by the \"free\" command - see [here](https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory) for more",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "psutil_mem",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'used')::float8) as \"used\",\n  avg((data->'total')::float8) as \"total\",\n  avg((data->'available')::float8) as \"available\",\n  avg((data->'free')::float8) as \"free\",\n  avg((data->'buff_cache')::float8) as \"buff_cache\"\nFROM\n  psutil_mem\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage ($agg_interval avg.)",
   "type": "graph",
   "description": "NB! Doesn't have to necessarily equal 100%  to values reported by the \"free\" command - see [here](https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory) for more",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "swap_used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "psutil_mem",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'swap_used')::float8) as \"swap_used\",\n  avg((data->'swap_total')::float8) as \"swap_total\"\nFROM\n  psutil_mem\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Host disk IO Totals ($agg_interval aggregate)",
   "type": "graph",
   "description": "NB! For all disks on the host, not only Postgres related",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "read_bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "psutil_disk_io_total",
     "rawSql": "SELECT * FROM (\nSELECT\n  $__timeGroup(time, $agg_interval),\n  max((data->'read_bytes')::int8) - min((data->'read_bytes')::int8) as \"read_bytes\",\n  max((data->'write_bytes')::int8) - min((data->'write_bytes')::int8)  as \"write_bytes\"\nFROM\n  psutil_disk_io_total\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\n) x WHERE read_bytes >= 0 and write_bytes >= 0\nORDER BY 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage %",
   "type": "graph",
   "description": "For Postgres data / WAL / log folder partitions and user defined tablespace partitions",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_dir_or_tablespace]] ([[tag_path]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dir_or_tablespace" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "psutil_disk",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  (tag_data->>'dir_or_tablespace') || ' (' || (tag_data->>'path') || ')',\n  avg((data->'percent')::float8) as \"percent\"\nFROM\n  psutil_disk\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1, 2\nORDER BY 1, 2",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk space available",
   "type": "graph",
   "description": "For Postgres data / WAL / log folder partitions and user defined tablespace partitions",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_dir_or_tablespace]] ([[tag_path]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dir_or_tablespace" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "psutil_disk",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  (tag_data->>'dir_or_tablespace') || ' (' || (tag_data->>'path') || ')',\n  avg((data->'free')::float8) as \"free\"\nFROM\n  psutil_disk\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1, 2\nORDER BY 1, 2",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2020/11/CYBERTEC_RGB_300x80px.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}