{{- if .Values.web.noAnonymous -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgwatch2.fullname" . }}-web
  labels:
{{ include "pgwatch2.labels" . | indent 4 }}
type: Opaque
data:
  user: {{ .Values.web.user | b64enc | quote }}
  {{- if .Values.web.password }}
  password: {{ .Values.web.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}