{{- if .Values.web.ingress.enabled -}}
{{- $fullName := include "pgwatch2.fullname" . -}}
{{- $svcPort := .Values.web.service.servicePort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-web
  labels:
{{ include "pgwatch2.labels" . | indent 4 }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.web.ingress.tls }}
  tls:
  {{- range .Values.web.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.web.ingress.host | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}-web
              servicePort: {{ $svcPort }}
{{- end }}
