{
 "title": "Single query details",
 "description": "For one query",
 "tags": [ "pgwatch2" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES WITH KEY = \"dbname\""
   },
   {
    "name": "queryid",
    "query": "show tag values from stat_statements with key = \"queryid\" WHERE dbname = '$dbname'"
   },
   { "name": "rate_unit", "query": "1s,1m,5m,10m,15m,30m,1h,1d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Avg. runtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "avg_runtime",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"total_time\")) / non_negative_derivative(mean(\"calls\")) FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($__interval), \"queryid\" fill(null)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Calls ($rate_unit rate)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Total runtime ($rate_unit rate)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "total_runtime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "sb_hit_ratio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"shared_blks_hit\")) / (non_negative_derivative(mean(\"shared_blks_hit\")) + non_negative_derivative(mean(\"shared_blks_read\"))) * 100 FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($__interval), \"queryid\" fill(null)",
     "select": [
      [
       { "params": [ "shared_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "\"shared_blks_*\" info ($rate_unit rate)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "shared_blks_written",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "shared_blks_written" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "shared_blks_read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "shared_blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "shared_blks_hit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "shared_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "shared_blks_dirtied",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "shared_blks_dirtied" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Temp Blocks Read/Write rate ($rate_unit)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "temp_blks_written",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "temp_blks_written" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "temp_blks_read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "temp_blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend block Read/Write time ($rate_unit rate)",
   "type": "graph",
   "description": "FYI - blk_write_time can easily be 0 as normally changes happen only in the shared buffers and are written out by the checkpointer / background writer.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "blk_read_time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "blk_read_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "blk_write_time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "blk_write_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$rate_unit" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "% of total_time spent in direct IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "io_time_pct",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((non_negative_derivative(mean(\"blk_read_time\"))  + non_negative_derivative(mean(\"blk_write_time\"))) /  non_negative_derivative(mean(\"total_time\"))) * 100  FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($__interval), \"queryid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values FROM \"stat_statements\" WITH key = \"query\" WHERE \"queryid\" = '$queryid'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2020/11/CYBERTEC_RGB_300x80px.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}