{
 "title": "Sessions overview",
 "tags": [
  "pgwatch2",
  "postgres"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbname", "query": { "query": "label_values(dbname)" } },
   { "name": "agg_interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "TPS / QPS ($agg_interval avg.)",
   "type": "graph",
   "description": "NB! QPS is an approximation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pgwatch2_db_stats_xact_commit{dbname=\"$dbname\"}[$agg_interval]) + rate(pgwatch2_db_stats_xact_rollback{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "TPS"
    },
    {
     "expr": "rate(pgwatch2_stat_statements_calls_calls{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Session activity ($agg_interval avg., log base 2)",
   "type": "graph",
   "description": "NB! QPS is an approximation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(pgwatch2_backends_total{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Total"
    },
    {
     "expr": "avg_over_time(pgwatch2_backends_active{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Active"
    },
    {
     "expr": "pgwatch2_backends_max_connections{dbname=\"$dbname\"}",
     "legendFormat": "Max. configured"
    },
    {
     "expr": "avg_over_time(pgwatch2_backends_waiting{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Waiting"
    },
    {
     "expr": "max_over_time(pgwatch2_backends_idleintransaction{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Idle in TX"
    },
    {
     "expr": "increase(pgwatch2_db_stats_deadlocks{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "title": "Longest query duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pgwatch2_backends_longest_query_seconds{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Longest query "
    },
    {
     "expr": "avg_over_time(pgwatch2_backends_longest_query_seconds{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Avg. query"
    }
   ]
  },
  {
   "title": "Longest TX duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pgwatch2_backends_longest_tx_seconds{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Longest TX"
    },
    {
     "expr": "avg_over_time(pgwatch2_backends_avg_tx_seconds{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Avg. TX"
    }
   ]
  },
  {
   "title": "Longest wait duration",
   "type": "graph",
   "description": "\"No data\" means no waiting detected",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pgwatch2_backends_longest_waiting_seconds{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Longest query duration"
    },
    {
     "expr": "avg_over_time(pgwatch2_backends_avg_waiting_seconds{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Avg. query duration"
    }
   ]
  },
  {
   "title": "Autovacuum max. duration / # workers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pgwatch2_backends_longest_autovacuum_seconds{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "AV duration"
    },
    {
     "expr": "max_over_time(pgwatch2_backends_av_workers{dbname=\"$dbname\"}[$agg_interval])",
     "legendFormat": "Active AV workers"
    }
   ]
  }
 ]
}