{
 "title": "Server Log Events",
 "description": "Assumes local (on DB server) setup and CSVLOG output format",
 "tags": [ "pgwatch2" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES FROM \"server_log_event_counts\" WITH KEY = \"dbname\""
   },
   { "name": "agg_interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Server log events (DB)",
   "type": "graph",
   "description": "Based on 'server_log_event_counts' metric. Assumes local (on DB server) setup and CSVLOG output format",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server_log_event_counts",
     "query": "SELECT\n  sum(\"debug\") as \"debug\",\n  sum(\"log\") as \"log\",\n  sum(\"notice\") as \"notice\",\n  sum(\"warning\") as \"warning\",\n  sum(\"error\") as \"error\",\n  sum(\"fatal\") as \"fatal\",\n  sum(\"panic\") as \"panic\"\nFROM \"server_log_event_counts\"\nWHERE (\"dbname\" =~ /^$dbname$/)\nAND $timeFilter\nGROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "debug" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Server log events (whole instance)",
   "type": "graph",
   "description": "Based on 'server_log_event_counts' metric. Assumes local (on DB server) setup and CSVLOG output format",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  sum(\"debug_total\") as \"debug\",\n  sum(\"log_total\") as \"log\",\n  sum(\"notice_total\") as \"notice\",\n  sum(\"warning_total\") as \"warning\",\n  sum(\"error_total\") as \"error\",\n  sum(\"fatal_total\") as \"fatal\",\n  sum(\"panic_total\") as \"panic\"\nFROM \"server_log_event_counts\"\nWHERE (\"dbname\" =~ /^$dbname$/)\nAND $timeFilter\nGROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top ERROR generating DBs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select dbname, top(\"ERROR\", 20) as \"ERROR\", \"ERROR_TOTAL\" , \"FATAL\",  \"FATAL_TOTAL\" from (\nSELECT\n  sum(error) as \"ERROR\",\n  sum(error_total) as \"ERROR_TOTAL\",\n  sum(fatal) as \"FATAL\",  \n  sum(fatal_total) as \"FATAL_TOTAL\"\nFROM\n  server_log_event_counts\nWHERE\n $timeFilter\n AND dbname =~ /^$dbname$/\nGROUP BY\n  time(365d), dbname\nFILL(none)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top FATAL generating instances",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select dbname, top(\"FATAL_TOTAL\", 20) as \"FATAL_TOTAL\",  \"FATAL\",  \"ERROR\", \"ERROR_TOTAL\" from (\nSELECT\n  sum(error) as \"ERROR\",\n  sum(error_total) as \"ERROR_TOTAL\",\n  sum(fatal) as \"FATAL\",  \n  sum(fatal_total) as \"FATAL_TOTAL\"\nFROM\n  server_log_event_counts\nWHERE\n $timeFilter\n AND dbname =~ /^$dbname$/\nGROUP BY\n  time(365d), dbname\nFILL(none)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2020/11/CYBERTEC_RGB_300x80px.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}