{
 "title": "Single query details",
 "description": "For one query",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES WITH KEY = \"dbname\""
   },
   {
    "name": "queryid",
    "query": "show tag values from stat_statements with key = \"queryid\" WHERE dbname = '$dbname'"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg. runtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "avg_runtime",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"total_time\"), 1h) / non_negative_derivative(mean(\"calls\"), 1h) FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($interval), \"queryid\" fill(null)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Calls (1h ratio)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "calls",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Total runtime (1h ratio)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "total_runtime",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "sb_hit_ratio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"shared_blks_hit\"), 1h) / (non_negative_derivative(mean(\"shared_blks_hit\"), 1h) + non_negative_derivative(mean(\"shared_blks_read\"), 1h)) * 100 FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($interval), \"queryid\" fill(null)",
     "select": [
      [
       { "params": [ "shared_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Temp Blocks Read/Write ratio (1h)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "temp_blks_written",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "temp_blks_written" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "temp_blks_read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "temp_blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Read/Write time (1h ratio)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "blk_read_time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "blk_read_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "blk_write_time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "select": [
      [
       { "params": [ "blk_write_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Time (%) spent in IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "io_time_pct",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((non_negative_derivative(mean(\"blk_read_time\"), 1h)  + non_negative_derivative(mean(\"blk_write_time\"), 1h)) /  non_negative_derivative(mean(\"total_time\"), 1h)) * 100  FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($interval), \"queryid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "show tag values FROM \"stat_statements\" WITH key = \"query\" WHERE \"queryid\" = '$queryid'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2017/11/Cybertec_Logo_2017_300px_slogan_trans.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}