{
 "title": "Vmstat",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM vmstat ORDER BY 1;"
   },
   {
    "name": "agg_interval",
    "query": "1s,1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'us')::int) as us,\n  avg((data->'sy')::int) as sy,\n  avg((data->'id')::int) as id,\n  avg((data->'wa')::int) as wa,\n  avg((data->'st')::int) as st\nFROM\n  vmstat\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'bi')::int8) as bi,\n  avg((data->'bo')::int8) as bo\nFROM\n  vmstat\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Swap IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'si')::int8) as si,\n  avg((data->'so')::int8) as so\nFROM\n  vmstat\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'free')::int8) as free,\n  avg((data->'buff')::int8) as buff,\n  avg((data->'cache')::int8) as cache,\n  avg((data->'swpd')::int8) as swpd\nFROM\n  vmstat\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Procs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'r')::int8) as r,\n  avg((data->'b')::int8) as b\nFROM\n  vmstat\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "System",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->'in')::int8) as in,\n  avg((data->'cs')::int8) as cs\nFROM\n  vmstat\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  }
 ]
}