{
 "title": "Table details time lag comparison",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics ORDER BY 1;"
   },
   {
    "name": "table_full_name",
    "query": "SELECT DISTINCT tag_data->>'table_full_name' FROM table_stats WHERE time > now() - '1d'::interval AND dbname = '$dbname' ORDER BY 1"
   },
   {
    "name": "agg_interval",
    "query": "1s,1m,2m,3m,5m,10m,15m,30m,1h,6h,12h,1d,7d"
   },
   { "name": "lag_interval", "query": "1h,6h,12h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "INSERT-s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(ins-ins_lag) as \"INSERT\"\nfrom (\n        select \n          (data->'n_tup_ins')::int8 as ins,\n          lag((data->'n_tup_ins')::int8) over w as ins_lag,\n          time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and $__timeFilter(time)\n        window w as (order by time)\n\n) x\nwhere ins >= ins_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(ins-ins_lag) as \"INSERT-$lag_interval\"\nfrom (\n        select \n          (data->'n_tup_ins')::int8 as ins,\n          lag((data->'n_tup_ins')::int8) over w as ins_lag,\n          time + '$lag_interval'::interval as time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        window w as (order by time)\n\n) x\nwhere ins >= ins_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "UPDATE-s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(upd-upd_lag) as \"UPDATE\"\nfrom (\n        select \n          (data->'n_tup_upd')::int8 as upd,\n          lag((data->'n_tup_upd')::int8) over w as upd_lag,\n          time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and $__timeFilter(time)\n        window w as (order by time)\n\n) x\nwhere upd >= upd_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(upd-upd_lag) as \"UPDATE-$lag_interval\"\nfrom (\n        select \n          (data->'n_tup_upd')::int8 as upd,\n          lag((data->'n_tup_upd')::int8) over w as upd_lag,\n          time + '$lag_interval'::interval as time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        window w as (order by time)\n\n) x\nwhere upd >= upd_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "DELETE-s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(del-del_lag) as \"DELETE\"\nfrom (\n        select \n          (data->'n_tup_del')::int8 as del,\n          lag((data->'n_tup_del')::int8) over w as del_lag,\n          time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and $__timeFilter(time)\n        window w as (order by time)\n\n) x\nwhere del >= del_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(del-del_lag) as \"DELETE-$lag_interval\"\nfrom (\n        select \n          (data->'n_tup_del')::int8 as del,\n          lag((data->'n_tup_del')::int8) over w as del_lag,\n          time + '$lag_interval'::interval as time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        window w as (order by time)\n\n) x\nwhere del >= del_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Seq. Scan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum(seq_scan-seq_scan_lag) as seq_scan\nFROM (  \n  SELECT\n    (data->'seq_scan')::int8 as seq_scan, lag((data->'seq_scan')::int8) over w as seq_scan_lag,\n    time\n  FROM\n    table_stats\n  WHERE\n    $__timeFilter(time) AND dbname = '$dbname'\n    AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE seq_scan >= seq_scan_lag\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum(seq_scan-seq_scan_lag) as \"seq_scan-$lag_interval\"\nFROM (  \n  SELECT\n    (data->'seq_scan')::int8 as seq_scan, lag((data->'seq_scan')::int8) over w as seq_scan_lag,\n    time + '$lag_interval'::interval as time\n  FROM\n    table_stats\n  WHERE\n    time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n    AND dbname = '$dbname'\n    AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE seq_scan >= seq_scan_lag\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Idx. Scan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum(idx_scan-idx_scan_lag) as idx_scan\nFROM (  \n  SELECT\n    (data->'idx_scan')::int8 as idx_scan, lag((data->'idx_scan')::int8) over w as idx_scan_lag,\n    time\n  FROM\n    table_stats\n  WHERE\n    $__timeFilter(time) AND dbname = '$dbname'\n    AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE idx_scan >= idx_scan_lag\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum(idx_scan-idx_scan_lag) as \"idx_scan-$lag_interval\"\nFROM (  \n  SELECT\n    (data->'idx_scan')::int8 as idx_scan, lag((data->'idx_scan')::int8) over w as idx_scan_lag,\n    time + '$lag_interval'::interval as time\n  FROM\n    table_stats\n  WHERE\n    time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n    AND dbname = '$dbname'\n    AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE idx_scan >= idx_scan_lag\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Shared buffers hit rate - Heap",
   "type": "timeseries",
   "description": "i.e. the main table  excluding indexes and TOAST",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  avg( case when hh = hh_lag and hr = hr_lag then null else (hh-hh_lag)::numeric * 100 / (hh-hh_lag+hr-hr_lag) end ) as \"Heap hit\"\nfrom (\n        select \n          (data->'heap_blks_hit')::int8 as hh, lag((data->'heap_blks_hit')::int8) over w as hh_lag,\n          (data->'heap_blks_read')::int8 as hr, lag((data->'heap_blks_read')::int8) over w as hr_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hh >= hh_lag and hr >= hr_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  avg( case when hh = hh_lag and hr = hr_lag then null else (hh-hh_lag)::numeric * 100 / (hh-hh_lag+hr-hr_lag) end ) as \"Heap hit-$lag_interval\"\nfrom (\n        select \n          (data->'heap_blks_hit')::int8 as hh, lag((data->'heap_blks_hit')::int8) over w as hh_lag,\n          (data->'heap_blks_read')::int8 as hr, lag((data->'heap_blks_read')::int8) over w as hr_lag,\n          time +'$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hh >= hh_lag and hr >= hr_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Shared buffers hit rate - Toast",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  100 * avg( case when tr = tr_lag and th = th_lag and tir = tir_lag and tih = tir_lag then null else (coalesce(th,0)-coalesce(th_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0))::numeric / (coalesce(th,0)-coalesce(th_lag,0) + coalesce(tr,0)-coalesce(tr_lag,0) + coalesce(tir,0)-coalesce(tir_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0)) end ) as \"Toast hit\"\nfrom (\n        select \n          (data->'toast_blks_read')::int8 as tr, lag((data->'toast_blks_read')::int8) over w as tr_lag,\n          (data->'toast_blks_hit')::int8 as th, lag((data->'toast_blks_hit')::int8) over w as th_lag,\n          (data->'tidx_blks_read')::int8 as tir, lag((data->'tidx_blks_read')::int8) over w as tir_lag,\n          (data->'tidx_blks_hit')::int8 as tih, lag((data->'tidx_blks_hit')::int8) over w as tih_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere th > th_lag or tih > tih_lag or tr > tr_lag or tir > tir_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  100 * avg( case when tr = tr_lag and th = th_lag and tir = tir_lag and tih = tir_lag then null else (coalesce(th,0)-coalesce(th_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0))::numeric / (coalesce(th,0)-coalesce(th_lag,0) + coalesce(tr,0)-coalesce(tr_lag,0) + coalesce(tir,0)-coalesce(tir_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0)) end ) as \"Toast hit-$lag_interval\"\nfrom (\n        select \n          (data->'toast_blks_read')::int8 as tr, lag((data->'toast_blks_read')::int8) over w as tr_lag,\n          (data->'toast_blks_hit')::int8 as th, lag((data->'toast_blks_hit')::int8) over w as th_lag,\n          (data->'tidx_blks_read')::int8 as tir, lag((data->'tidx_blks_read')::int8) over w as tir_lag,\n          (data->'tidx_blks_hit')::int8 as tih, lag((data->'tidx_blks_hit')::int8) over w as tih_lag,\n          time + '$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere th > th_lag or tih > tih_lag or tr > tr_lag or tir > tir_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Block bandwidth - Heap",
   "type": "timeseries",
   "description": "Assuming 8k blocks. Hit + read",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(hh-hh_lag+hr-hr_lag) as \"Heap read\"\nfrom (\n        select \n          (data->'heap_blks_hit')::int8 as hh, lag((data->'heap_blks_hit')::int8) over w as hh_lag,\n          (data->'heap_blks_read')::int8 as hr, lag((data->'heap_blks_read')::int8) over w as hr_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hr >= hr_lag and hh >= hh_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(hh-hh_lag+hr-hr_lag) as \"Heap read-$lag_interval\"\nfrom (\n        select \n          (data->'heap_blks_hit')::int8 as hh, lag((data->'heap_blks_hit')::int8) over w as hh_lag,\n          (data->'heap_blks_read')::int8 as hr, lag((data->'heap_blks_read')::int8) over w as hr_lag,\n          time + '$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hr >= hr_lag and hh >= hh_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Block bandwidth - Indexes",
   "type": "timeseries",
   "description": "Assuming 8k blocks. Hit + read",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(ih-ih_lag+ir-ir_lag) as \"Idx read\"\nfrom (\n        select \n          (data->'idx_blks_hit')::int8 as ih, lag((data->'idx_blks_hit')::int8) over w as ih_lag,\n          (data->'idx_blks_read')::int8 as ir, lag((data->'idx_blks_read')::int8) over w as ir_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere ir >= ir_lag and ih >= ih_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(ih-ih_lag+ir-ir_lag) as \"Idx read-$lag_interval\"\nfrom (\n        select \n          (data->'idx_blks_hit')::int8 as ih, lag((data->'idx_blks_hit')::int8) over w as ih_lag,\n          (data->'idx_blks_read')::int8 as ir, lag((data->'idx_blks_read')::int8) over w as ir_lag,\n          time + '$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere ir >= ir_lag and ih >= ih_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Block bandwidth - Toast",
   "type": "timeseries",
   "description": "Assuming 8k blocks. Hit + read",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(coalesce(th,0)-coalesce(th_lag,0) + coalesce(tr,0)-coalesce(tr_lag,0) + coalesce(tir,0)-coalesce(tir_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0)) as \"Toast read\"\nfrom (\n        select \n          (data->'toast_blks_read')::int8 as tr, lag((data->'toast_blks_read')::int8) over w as tr_lag,\n          (data->'toast_blks_hit')::int8 as th, lag((data->'toast_blks_hit')::int8) over w as th_lag,\n          (data->'tidx_blks_read')::int8 as tir, lag((data->'tidx_blks_read')::int8) over w as tir_lag,\n          (data->'tidx_blks_hit')::int8 as tih, lag((data->'tidx_blks_hit')::int8) over w as tih_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere th > th_lag or tih > tih_lag or tr > tr_lag or tir > tir_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(coalesce(th,0)-coalesce(th_lag,0) + coalesce(tr,0)-coalesce(tr_lag,0) + coalesce(tir,0)-coalesce(tir_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0)) as \"Toast read-$lag_interval\"\nfrom (\n        select \n          (data->'toast_blks_read')::int8 as tr, lag((data->'toast_blks_read')::int8) over w as tr_lag,\n          (data->'toast_blks_hit')::int8 as th, lag((data->'toast_blks_hit')::int8) over w as th_lag,\n          (data->'tidx_blks_read')::int8 as tir, lag((data->'tidx_blks_read')::int8) over w as tir_lag,\n          (data->'tidx_blks_hit')::int8 as tih, lag((data->'tidx_blks_hit')::int8) over w as tih_lag,\n          time + '$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere th > th_lag or tih > tih_lag or tr > tr_lag or tir > tir_lag\ngroup by 1\norder by 1"
    }
   ]
  }
 ]
}