{
 "title": "Stat_statements overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES WITH KEY = \"dbname\""
   },
   {
    "name": "min_calls",
    "label": "min. \"pg_stat_statements.calls\"",
    "query": "1,10,100,1000,10000"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg. query runtime by \"queryid\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_queryid",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"total_time\"), 1h) / non_negative_derivative(mean(\"calls\"), 1h) as avg_runtime FROM \"stat_statements\" WHERE \"dbname\" =~ /^$dbname$/ AND calls > $min_calls AND $timeFilter GROUP BY time($__interval), \"queryid\" fill(none)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cumulative 1h query runtime by \"queryid\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_queryid",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"total_time\"), 1h) FROM \"stat_statements\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter AND calls >= $min_calls GROUP BY time($__interval), \"queryid\" fill(none)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Calls per 1h by \"queryid\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_queryid",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"calls\"), 1h) FROM \"stat_statements\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter AND calls >= $min_calls GROUP BY time($__interval), \"queryid\" fill(none)",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2019/05/Cybertec_Logo_wei%C3%9F-transparent_300x80px-01.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}