apiVersion: v1
kind: Secret
metadata:
  name: pgwatch2-monitoreddb
type: Opaque
stringData:
  monitoreddb.yaml: |-
{{- range $key, $val := .Values.monitoredDbs }}
    - unique_name: {{ $key }}
      dbtype: postgres
      host: {{ .host }}
      port: {{ .port }}
      dbname: {{ .dbname }}
      user: {{ .username }}
      password: {{ .password }}
      sslmode: require
      stmt_timeout: 15
      is_superuser: false
      is_enabled: true
      group: default
      sslrootcert: ""
      sslcert: ""
      sslkey: ""
      custom_metrics:
        archiver: 60
        backends: 60
        bgwriter: 60
        change_events: 300
        db_stats: 60
        db_size: 300
        index_stats: 900
        locks: 60
        locks_mode: 60
        replication: 120
        replication_slots: 120
        settings: 7200
        sproc_stats: 180
        stat_activity_realtime: 30
        recommendations: 43200
        stat_statements: 60
        stat_statements_calls: 60
        table_bloat_approx_summary_sql: 7200
        table_io_stats: 600
        table_stats: 300
        wal: 60
        wal_receiver: 120
{{ end }}
{{- range $key, $val := .Values.monitoredPools }}
    - unique_name: {{ $key }}
      dbtype: pgbouncer
      host: {{ .host }}
      port: {{ .port }}
      dbname: {{ .dbname }}
      user: {{ .username }}
      password: {{ .password }}
      sslmode: require
      stmt_timeout: 15
      is_superuser: false
      is_enabled: true
      group: default
      sslrootcert: ""
      sslcert: ""
      sslkey: ""
      custom_metrics:
        pgbouncer_stats: 60
{{ end }}
