{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pgwatch2.serviceAccountName" . }}
  labels:
{{ include "pgwatch2.labels" . | indent 4 }}
{{- end -}}
