- unique_name: pgbouncer
  dbtype: pgbouncer
  host: 127.0.0.1
  port: 6432
  dbname: postgres 
  user: pgwatch2
  sslmode: disable    
  is_superuser: false 
  custom_metrics: 
    pgbouncer_stats: 10
    pgbouncer_clients: 10
  is_enabled: true
  sslrootcert: ''
  sslcert: ''
  sslkey: ''

