{
 "title": "Replication",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "# Non-active replication slots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "select sum(\"last\") from (select last(\"non_active_int\") FROM \"replication_slots\" WHERE  $timeFilter group by \"dbname\", \"slot_name\")",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slot max. restart_lsn lag",
   "type": "singlestat",
   "description": "Based on pg_replication_slots",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "SELECT max(\"restart_lsn_lag_b\") FROM \"replication_slots\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "restart_lsn_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max. write lag",
   "type": "singlestat",
   "description": "NB! Data is available  only on connected replicas!",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT max(\"write_lag_b\") FROM \"replication\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "write_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max. replay lag",
   "type": "singlestat",
   "description": "NB! Data is available  only on connected replicas!",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT max(\"replay_lag_b\") FROM \"replication\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "replay_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication slot restart_lsn lag",
   "type": "graph",
   "description": "Based on pg_replication_slots.  Primary only",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_dbname]] slot=[[tag_slot_name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "slot_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "SELECT mean(\"restart_lsn_lag_b\") FROM \"replication_slots\" WHERE $timeFilter GROUP BY time($interval), \"dbname\", \"slot_name\" fill(none)",
     "select": [
      [
       { "params": [ "restart_lsn_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication write lag",
   "type": "graph",
   "description": "Based on pg_stat_replication on primaries. NB! Data is available  only on connected replicas!",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_dbname]] [[tag_application_name]] [[tag_client_info]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "client_info" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT mean(\"lag_b\") FROM \"replication\" WHERE $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "write_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication replay lag",
   "type": "graph",
   "description": "Based on pg_stat_replication on primaries. NB! Data is available  only on connected replicas!",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_dbname]] [[tag_application_name]] [[tag_client_info]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "client_info" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT mean(\"lag_b\") FROM \"replication\" WHERE $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "replay_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repl. slot XMIN age",
   "type": "graph",
   "description": "Based on pg_replication_slots.xmin",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_dbname]] [[tag_application_name]] [[tag_client_info]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "client_info" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "SELECT mean(\"xmin_age_tx\") FROM \"replication_slots\" WHERE $timeFilter GROUP BY time($__interval), \"dbname\", \"client_info\", \"application_name\" fill(none)",
     "select": [
      [
       { "params": [ "xmin_age_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}