FROM ubuntu:22.04

RUN apt-get -q update && DEBIAN_FRONTEND=noninteractive apt-get install -qy curl ca-certificates gnupg \
  && echo "deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
  && curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && apt-get -q update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -qy postgresql-client-15 wget unzip \
  && useradd -m -s /bin/bash postgres

USER postgres

COPY pgwatch2/sql/ /pgwatch2/sql
COPY docker/launch-wrapper-db-bootstrapper-heroku.sh /pgwatch2/launch-wrapper-db-bootstrapper-heroku.sh

ENV PGSSLMODE require
ENV ON_ERROR_STOP 1

# configdb | metricsdb. Required
ENV BOOTSTRAP_TYPE configdb

ENV BOOTSTRAP_ADD_TEST_MONITORING_ENTRY 1

# TODO only metric-time is supported currently
# metric-time | metric-dbname-time | timescale
ENV BOOTSTRAP_METRICSDB_SCHEMA_TYPE metric-time

CMD ["/pgwatch2/launch-wrapper-db-bootstrapper-heroku.sh"]