{
 "title": "Replication",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES FROM \"replication\", \"replication_slots\" WITH KEY = \"dbname\""
   }
  ]
 },
 "panels": [
  {
   "title": "Inactive repl. slots",
   "type": "singlestat",
   "description": "Based on last 5m data.  > 1 ~ Error. Causes WAL accumulation on the master and possibly autovacuum inefficiencies",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "select sum(\"last\") from (select last(\"non_active_int\") FROM \"replication_slots\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter group by \"dbname\", \"slot_name\")",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active repl. slots",
   "type": "singlestat",
   "description": "Based on last 5m data. FYI - no thresholds defined",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "select count(\"active\") from (select last(\"active\") as \"active\" FROM \"replication_slots\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter group by \"dbname\", \"slot_name\") WHERE \"active\" =  true",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active replicas",
   "type": "singlestat",
   "description": "NB! Data is available  only on connected replicas. No thresholds by default",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "select count(\"last\") from (SELECT last(\"state\") FROM \"replication\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(1d), dbname, client_info fill(none)) where \"last\" = 'streaming'",
     "select": [
      [
       { "params": [ "replay_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Active \"sync\" replicas",
   "type": "singlestat",
   "description": "NB! Data is available  only on connected replicas. No thresholds by default",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "select sum(\"last\") from (SELECT last(\"is_sync_int\") FROM \"replication\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(1d), dbname, client_info fill(none))",
     "select": [
      [
       { "params": [ "replay_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Slot max. restart_lsn lag",
   "type": "singlestat",
   "description": "Based on last 5m of \"pg_replication_slots.restart_lsn\" and translates to \"overhead\" WAL folder size",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "SELECT max(\"restart_lsn_lag_b\") FROM \"replication_slots\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "restart_lsn_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max. write lag",
   "type": "singlestat",
   "description": "NB! Data is available  only on connected replicas! Based on last 5m data.",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT max(\"write_lag_b\") FROM \"replication\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "write_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max. flush lag",
   "type": "singlestat",
   "description": "NB! Data is available  only on connected replicas! Based on last 5m data.",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT max(\"write_lag_b\") FROM \"replication\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "flush_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max. replay lag",
   "type": "singlestat",
   "description": "NB! Data is available  only on connected replicas! Based on last 5m data.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT max(\"replay_lag_b\") FROM \"replication\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "replay_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication slot restart_lsn lag (primary extra WAL size)",
   "type": "graph",
   "description": "Based on pg_replication_slots.  Primary only",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_dbname]] slot=[[tag_slot_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "slot_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "SELECT mean(\"restart_lsn_lag_b\") FROM \"replication_slots\" WHERE $timeFilter GROUP BY time($interval), \"dbname\", \"slot_name\" fill(none)",
     "select": [
      [
       { "params": [ "restart_lsn_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication flush lag",
   "type": "graph",
   "description": "Based on pg_stat_replication on primaries. NB! Data is available  only on connected replicas!",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_dbname]] [[tag_application_name]] [[tag_client_info]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "client_info" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT mean(\"write_lag_b\") FROM \"replication\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time($__interval), \"dbname\", \"client_info\", \"application_name\" fill(none)",
     "select": [
      [
       { "params": [ "flush_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication replay lag",
   "type": "graph",
   "description": "Based on pg_stat_replication on primaries. NB! Data is available  only on connected replicas!",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_dbname]] [[tag_application_name]] [[tag_client_info]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "client_info" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication",
     "query": "SELECT mean(\"lag_b\") FROM \"replication\" WHERE $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "replay_lag_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Repl. slot XMIN age (in transactions)",
   "type": "graph",
   "description": "Based on \"pg_replication_slots.xmin\". The oldest transaction that this slot needs the database to retain. VACUUM cannot remove tuples deleted by any later transaction.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_dbname]] [[tag_slot_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "slot_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "SELECT mean(\"xmin_age_tx\") FROM \"replication_slots\" WHERE $timeFilter GROUP BY time($__interval), \"dbname\", \"plugin\", \"slot_name\" fill(none)",
     "select": [
      [
       { "params": [ "xmin_age_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2017/11/Cybertec_Logo_2017_300px_slogan_trans.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}