{
 "title": "Health-check",
 "description": "Current and avg. KPI-s. Expects 'get_load_average' and 'backends'  helpers to be installed on the monitored DB.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM public.all_distinct_dbname_metrics ORDER BY 1;"
   },
   { "name": "online_interval", "label": "Max. age for 'online' metrics", "query": "1m,3m,5m,10m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Instance state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "select last(\"in_recovery_int\") FROM \"wal\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(365d) fill(none)",
     "rawSql": "SELECT\n  time,\n  (data->'in_recovery_int')::int\nFROM\n  wal\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Instance uptime",
   "type": "singlestat",
   "description": "< 5m Error, < 30m Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "SELECT\n  time,\n  (data->'postmaster_uptime_s')::int\nFROM\n  wal\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "WAL archiving status",
   "type": "singlestat",
   "description": "Based on pg_stat_archiver. N/A when archiving is not enabled.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "archiver",
     "rawSql": "SELECT\n  time,\n  (data->'is_failing_int')::int\nFROM\n  archiver\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU load (avg.)",
   "type": "singlestat",
   "description": "Assumes get_load_average helper being installed. 25 Warn / 50  Error  thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "rawSql": "SELECT\n  time,\n  (data->'load_1min')::float8\nFROM\n  cpu_load\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Backends",
   "type": "singlestat",
   "description": "< 1 Warn / > 300 Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "SELECT\n  time,\n  (data->'numbackends')::int\nFROM\n  db_stats\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked backends",
   "type": "singlestat",
   "description": "1 Warn / 5 Err thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT last(\"idleintransaction\") FROM \"backends\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(15m) fill(none)",
     "rawSql": "SELECT\n  time,\n  (data->'waiting')::int\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "\"Idle in TX\" count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT last(\"idleintransaction\") FROM \"backends\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(15m) fill(none)",
     "rawSql": "SELECT\n  time,\n  (data->'idleintransaction')::int\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Longest query runtime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "rawSql": "SELECT\n  time,\n  (data->'longest_query_seconds')::int\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "TX error pct. (avg.)",
   "type": "singlestat",
   "description": "0.5% Warn / 1% Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT (non_negative_derivative(mean(\"xact_rollback\")) / (non_negative_derivative(mean(\"xact_commit\")) + non_negative_derivative(mean(\"xact_rollback\"))) * 100) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n  $__timeGroup(time, $online_interval),\n  max((roll-roll_lag)::numeric / ((roll-roll_lag) + (comm-comm_lag)))*100 as \"TX rollback ratio\"\nfrom (\n  select\n      time,\n      (data->>'xact_rollback')::int8 as roll, lag((data->>'xact_rollback')::int8) over w as roll_lag,\n      (data->>'xact_commit')::int8 as comm, lag((data->>'xact_commit')::int8) over w as comm_lag\n  FROM\n      db_stats\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n    window w as (order by time)\n) x\nWHERE comm > comm_lag or roll > roll_lag\nGROUP BY 1\nORDER BY 1 DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "TPS (avg.)",
   "type": "singlestat",
   "description": "Transactions per Second. Last $online_interval average. <0.1 % Error / < 1.0 Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"xact_commit\"), 1s) + non_negative_derivative(last(\"xact_rollback\"), 1s) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n  $__timeGroup(time, $online_interval),\n  avg( ((roll-roll_lag) + (comm-comm_lag)) / extract(epoch from (time - time_lag))  )\nfrom (\n  select\n      time, lag(time) over w as time_lag,\n      (data->>'xact_rollback')::int8 as roll, lag((data->>'xact_rollback')::int8) over w as roll_lag,\n      (data->>'xact_commit')::int8 as comm, lag((data->>'xact_commit')::int8) over w as comm_lag\n  FROM\n      db_stats\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n    window w as (order by time)\n) x\nWHERE (comm > comm_lag or roll > roll_lag) and time > time_lag\nGROUP BY 1\nORDER BY 1 DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "QPS (avg.)",
   "type": "singlestat",
   "description": "Queries per Second. Last $online_interval avg. < 0.1 Error / < 1 Warning thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT non_negative_derivative(last(\"calls\"), 1s) FROM \"stat_statements_calls\" WHERE $timeFilter AND \"dbname\" =~ /^$dbname$/ GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n  $__timeGroup(time, $online_interval),\n  avg( (c - c_lag) / extract(epoch from time - time_lag)) as qps\nfrom (\n        select \n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag\n        from stat_statements_calls\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1 desc\nlimit 1\n"
    }
   ]
  },
  {
   "title": "Query runtime (avg.)",
   "type": "singlestat",
   "description": "Last $online_interval avg. > 0.5s Warning / > 5s  Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "select mean(q) from (SELECT non_negative_derivative(mean(\"total_time\")) / non_negative_derivative(mean(\"calls\")) as q FROM \"stat_statements\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY queryid, time($__interval) fill(none)) group by time($__interval) fill(none)",
     "rawSql": "select\n$__timeGroup(time, $online_interval),\navg(case when c = c_lag then 0 else (tt-tt_lag)::numeric / (c-c_lag) end) as \"avg_query_runtime\"\nfrom (\n\n        select \n          (data->>'total_time')::float8 as tt, lag((data->>'total_time')::float8) over w as tt_lag,\n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time\n        from stat_statements_calls\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere c >= c_lag and tt >= tt_lag\ngroup by 1\norder by 1 desc\nlimit 1"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "select sum(\"last\") from (SELECT last(\"size_b\") FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(3650d) fill(none))",
     "rawSql": "SELECT\n  time,\n  (data->'size_b')::int8\nFROM\n  db_size\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "DB size change",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "select sum(diff) from (SELECT last(\"size_b\")  - first(\"size_b\") as diff FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY dbname, time(365d) fill(none))",
     "rawSql": "select\n  time,\n  last_value-first_value as size_diff\nfrom (\n  select\n    time,\n    first_value((data->>'size_b')::int8) over w,\n    last_value((data->>'size_b')::int8) over w\n  from\n    db_size\n  where \n    dbname = '$dbname' and $__timeFilter(time)\n  window w as (\n     order by time rows BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING\n  )\n) x\norder by 1 desc\nlimit 1"
    }
   ]
  },
  {
   "title": "DATADIR disk space left",
   "type": "singlestat",
   "description": "Assumes get_psutil_disk wrapper being installed. 10/50GB Warn/Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_changes",
     "query": "SELECT last(\"free\") FROM psutil_disk WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter AND dir_or_tablespace = 'data_directory' GROUP BY time(365d) fill(none)",
     "rawSql": "select\n  time,\n  (data->'free')::int8\nfrom\n  psutil_disk\nwhere \n  dbname = '$dbname' and $__timeFilter(time)\n  and tag_data->>'dir_or_tablespace' = 'data_directory'\norder by 1 desc\nlimit 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Approx. table bloat",
   "type": "singlestat",
   "description": "For tables and B-tree indexes",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "select sum(bloat) from (SELECT last(\"approx_free_space_b\") as bloat FROM \"table_bloat_approx_summary\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(1d) fill(none))",
     "rawSql": "SELECT\n  time,\n  (data->'approx_free_space_b')::int8\nFROM\n  table_bloat_approx_summary\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY 1 DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Config change events",
   "type": "singlestat",
   "description": ">1 Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_changes",
     "query": "SELECT count(\"event\") FROM \"configuration_changes\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(365d) fill(none)",
     "rawSql": "SELECT\n  0 as time,\n  count(*)\nFROM\n  configuration_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Table changes",
   "type": "singlestat",
   "description": ">1 Warn thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_changes",
     "query": "SELECT count(\"event\") FROM \"table_changes\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(365d) fill(none)",
     "rawSql": "SELECT\n  0 as time,\n  count(*)\nFROM\n  table_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints requested",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bgwriter",
     "rawSql": "SELECT\n  time,\n  (data->'checkpoints_req')::int\nFROM\n  bgwriter\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY time\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers hit pct.",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT ( non_negative_derivative(mean(\"blks_hit\")) / (non_negative_derivative(mean(\"blks_hit\")) + non_negative_derivative(mean(\"blks_read\")))) * 100 FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n  time,\n  ((hit-hit_lag)::numeric / ((hit-hit_lag) + (read-read_lag)))*100 as \"Shared buffers hit ratio\"\nfrom (\n        select \n          (data->>'blks_hit')::int8 as hit, lag((data->>'blks_hit')::int8) over w as hit_lag,\n          (data->>'blks_read')::int8 as read, lag((data->>'blks_read')::int8) over w as read_lag,\n          (data->>'xact_rollback')::int8 as roll, lag((data->>'xact_rollback')::int8) over w as roll_lag,\n          (data->>'xact_commit')::int8 as comm, lag((data->>'xact_commit')::int8) over w as comm_lag,\n          time\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere hit > hit_lag or read > read_lag\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Invalid indexes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "select sum(\"last\") from (select last(\"is_invalid_int\") from index_stats where \"dbname\" =~ /^$dbname$/  AND $timeFilter  group by \"index_full_name\")",
     "rawSql": "SELECT\n  0 as time,\n  sum((data->'is_invalid_int')::int)\nFROM\n  index_stats\nWHERE\n  time = (select max(time) from index_stats where $__timeFilter(time) AND dbname = '$dbname')\n  AND dbname = '$dbname'\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Duplicate indexes",
   "type": "singlestat",
   "description": "NB! 'N/A' displayed both when no duplicate indexes or no metrics data for index_stats",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "select count(\"count\") from (select count(\"index_def\") from (select last(\"index_def\") as \"index_def\" from index_stats where \"dbname\" =~ /^$dbname$/  and $timeFilter  group by \"table_full_name\", \"index_full_name\", \"index_def_hash\") group by \"table_full_name\", \"index_def_hash\") where \"count\" > 1",
     "rawSql": "SELECT\n  0 as time,\n  coalesce(sum(count-1), 0)\nFROM (\nSELECT\n  tag_data->>'table_full_name' as table_full_name,\n  data->>'index_def' as index_def,\n  count(*)\nFROM\n  index_stats\nWHERE\n  time = (select max(time) from index_stats where $__timeFilter(time) AND dbname = '$dbname')\n  AND dbname = '$dbname'\nGROUP BY 1, 2\nHAVING count(*) > 1\n) x\n"
    }
   ]
  },
  {
   "title": "Avg. time from last autovacuum (tbls > 100MB)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 10 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "SELECT mean(\"last\") FROM (SELECT last(\"seconds_since_last_vacuum\") FROM \"table_stats\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter AND  table_size_b >  100000000 GROUP BY time(1h) fill(none))",
     "rawSql": "SELECT\n  0 as time,\n  avg(seconds_since_last_vacuum)\nFROM (\nSELECT\n  (data->'seconds_since_last_vacuum')::int8 as seconds_since_last_vacuum\nFROM\n  table_stats\nWHERE\n  time = (select max(time) from table_stats where $__timeFilter(time) AND dbname = '$dbname')\n  AND dbname = '$dbname'\n  AND (data->'table_size_b')::int8 > 100000000\n) x",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Seq. scans on >100 MB tables per minute (avg.)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "select sum(\"last\") from (select last(\"scans\") from (SELECT non_negative_derivative(last(\"seq_scan\"), 1m) as \"scans\" FROM \"table_stats\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter AND table_size_b > 100000000 GROUP BY time($__interval), table_full_name fill(none)) group by table_full_name)",
     "rawSql": "SELECT\n  time,\n  sum((scan-scan_lag) * 60 / extract(epoch from (time-time_lag)))\nFROM (\n  SELECT\n    time, lag(time) over w as time_lag,\n    (data->'seq_scan')::int8 as scan, lag((data->'seq_scan')::int8) over w as scan_lag\n  FROM\n    table_stats\n  WHERE\n    $__timeFilter(time)\n    AND dbname = '$dbname'\n    AND (data->'table_size_b')::int8 > 100000000\n  WINDOW w AS (partition by tag_data->>'table_full_name' order by time)\n) x\nWHERE scan > scan_lag and time > time_lag\nGROUP BY 1\nORDER BY 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "WAL per second (avg.)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wal",
     "query": "SELECT non_negative_derivative(last(\"xlog_location_b\"), 1s) FROM \"wal\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n  0 as time,\n  avg((wal-wal_lag) / (etime-lag_etime)) as \"WAL rate\"\nfrom (\n        select \n          (data->>'xlog_location_b')::int8 as wal, lag((data->>'xlog_location_b')::int8) over w as wal_lag,\n          extract(epoch from time) as etime,\n          lag(extract(epoch from time)) over w as lag_etime,\n          time\n        from wal\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere wal >= wal_lag and etime > lag_etime",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Temp. bytes per second (avg.)",
   "type": "singlestat",
   "description": "10/100 Warn / Error by default",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  0 as time,\n  avg(case when tb-tb_lag > 0 then (tb-tb_lag) / (etime - lag_etime) else 0 end) as \"Temp bytes (1h rate)\"\nfrom (\n        select \n          (data->>'temp_bytes')::int8 as tb, lag((data->>'temp_bytes')::int8) over w as tb_lag,\n          (extract(epoch from time))::int8 as etime,\n          (lag(extract(epoch from time)) over w)::int8 as lag_etime\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere tb >= tb_lag and etime > lag_etime\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Repl. slot max. XMIN horizon",
   "type": "singlestat",
   "description": "In TX. Holds back VACUUM",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "365d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "select max(\"xmin_age_tx\") from  (SELECT last(\"xmin_age_tx\") as \"xmin_age_tx\" FROM \"replication_slots\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(365d), slot_name fill(none))\n",
     "rawSql": "SELECT\n  0 as time,\n  max((data->'xmin_age_tx')::int8)\nFROM\n  replication_slots\nWHERE\n  time = (select max(time) from replication_slots where $__timeFilter(time) AND dbname = '$dbname')\n  and dbname = '$dbname'  ",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend max. XMIN horizon (in TX)",
   "type": "singlestat",
   "description": "Holds back VACUUM",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "rawSql": "SELECT\n  0 as time,\n  max((data->'max_xmin_age_tx')::int8)\nFROM\n  backends\nWHERE\n  time = (select max(time) from replication_slots where $__timeFilter(time) AND dbname = '$dbname')\n  and dbname = '$dbname'",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "INSERT-s per minute (avg.)",
   "type": "singlestat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"tup_inserted\"), 1m)  FROM \"db_stats\"  WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n  time,\n  avg(((ins-ins_lag) * 60) / extract(epoch from time - time_lag))\nfrom (\n        select \n          (data->>'tup_inserted')::int8 as ins, lag((data->>'tup_inserted')::int8) over w as ins_lag,\n          time, lag(time) over w as time_lag\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere ins >= ins_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "UPDATE-s per minute (avg.)",
   "type": "singlestat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"tup_updated\"), 1m)  FROM \"db_stats\"  WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n  time,\n  avg(((upd-upd_lag) * 60) / extract(epoch from time - time_lag))\nfrom (\n        select \n          (data->'tup_updated')::int8 as upd, lag((data->'tup_updated')::int8) over w as upd_lag,\n          time, lag(time) over w as time_lag\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere upd >= upd_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "DELETE-s per minute (avg.)",
   "type": "singlestat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"tup_deleted\"), 1m)  FROM \"db_stats\"  WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "select\n  time,\n  avg(((del-del_lag) * 60) / extract(epoch from time - time_lag))\nfrom (\n        select \n          (data->'tup_deleted')::int8 as del, lag((data->'tup_deleted')::int8) over w as del_lag,\n          time, lag(time) over w as time_lag\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)\n) x\nwhere del >= del_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Inactive repl. slots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "replication_slots",
     "query": "select sum(last) from (select last(\"non_active_int\") FROM \"replication_slots\" WHERE \"dbname\" =~ /^$dbname$/  AND $timeFilter  group by \"slot_name\")",
     "rawSql": "SELECT\n  0 as time,\n  sum((data->'non_active_int')::int)\nFROM\n  replication_slots\nWHERE\n  time = (select max(time) from replication_slots where $__timeFilter(time) AND dbname = '$dbname')\n  AND dbname = '$dbname'\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2017/11/Cybertec_Logo_2017_300px_slogan_trans.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}