{
 "title": "Query details",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbname", "query": { "query": "label_values(dbname)" } },
   {
    "name": "queryid",
    "query": {
     "query": "label_values(pgwatch2_stat_statements_total_time{dbname=\"$dbname\"}, queryid) "
    }
   },
   {
    "name": "agg_interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg. runtime ($agg_interval avg.)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(pgwatch2_stat_statements_total_time{dbname='$dbname',queryid='$queryid'})) / max(increase(pgwatch2_stat_statements_calls{dbname='$dbname',queryid='$queryid'}))",
     "legendFormat": "avg_runtime"
    }
   ]
  },
  {
   "title": "Total runtime ($agg_interval tot.)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(pgwatch2_stat_statements_total_time{dbname='$dbname',queryid='$queryid'}))",
     "legendFormat": "total_time"
    }
   ]
  },
  {
   "title": "Calls ($agg_interval tot.)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(pgwatch2_stat_statements_calls{dbname='$dbname',queryid='$queryid'}))",
     "legendFormat": "calls"
    }
   ]
  },
  {
   "title": "Shared buffers hit ratio ($agg_interval avg.)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * max(increase(pgwatch2_stat_statements_shared_blks_hit{dbname='$dbname',queryid='$queryid'})) / (max(increase(pgwatch2_stat_statements_shared_blks_hit{dbname='$dbname',queryid='$queryid'})) + max(increase(pgwatch2_stat_statements_shared_blks_read{dbname='$dbname',queryid='$queryid'})))",
     "legendFormat": "sb_hit_ratio"
    }
   ]
  },
  {
   "title": "Temp Blocks Read/Written ($agg_interval tot.)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "8192 * max(increase(pgwatch2_stat_statements_temp_blks_written{dbname='$dbname',queryid='$queryid'}))",
     "legendFormat": "temp_blks_written"
    },
    {
     "expr": "8192 * max(increase(pgwatch2_stat_statements_temp_blks_read{dbname='$dbname',queryid='$queryid'}))",
     "legendFormat": "temp_blks_read"
    }
   ]
  },
  {
   "title": "Backend block Read/Write time ($agg_interval tot.)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(pgwatch2_stat_statements_blk_read_time{dbname='$dbname',queryid='$queryid'}))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "max(increase(pgwatch2_stat_statements_blk_write_time{dbname='$dbname',queryid='$queryid'}))",
     "legendFormat": "blk_write_time"
    }
   ]
  }
 ]
}