pgwatch2:
  testDBEnabled: true
  datastore: prometheus

web:
  service:
    type: ClusterIP
    servicePort: 8080
#    nodePort: 30000
  noAnonymous: false
#  user: pgwatch2
#  password: password
  ingress:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1

exporter:
  service:
    type: NodePort
    servicePort: 9187
    nodePort: 30001
  ingress:
    enabled: true

grafana:
  service:
    type: NodePort
    servicePort: 3000
    nodePort: 30002
  noAnonymous: false
  ingress:
    enabled: true
#  user: pgwatch2
#  password: password