{
 "title": "Stat statements Top",
 "tags": [ "pgwatch2" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES WITH KEY = \"dbname\""
   },
   { "name": "top", "query": "1,3,5,10,15,20,30,40,50" }
  ]
 },
 "panels": [
  {
   "title": "Top queries by total runtime",
   "type": "table",
   "description": "NB! If there has been a pg_stat_statement reset or a server crash in the selected timerange, the information is false",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "ass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"spread\", \"queryid\", \"query\", $top) FROM (SELECT spread(\"total_time\") FROM \"stat_statements\" WHERE $timeFilter AND \"dbname\" = '$dbname'  AND \"query\" !~ /extract.*::int8\\s+as\\s+epoch_ns\\s*,/  AND \"query\" !~ /\\/\\*\\s*pgwatch2_generated\\s*\\*\\//GROUP BY time(3650d), \"queryid\", \"query\" fill(none) ) WHERE spread > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top queries by avg. runtime",
   "type": "table",
   "description": "NB! If there has been a pg_stat_statement reset or a server crash in the selected timerange, the information is false",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "ass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(avg, \"queryid\", \"query\", $top) AS top from (select mean(t) / mean(c) AS avg from (SELECT spread(\"total_time\") AS t, spread(\"calls\") AS c FROM \"stat_statements\" WHERE $timeFilter AND dbname = '$dbname' AND \"query\" !~ /extract.*::int8\\s+as\\s+epoch_ns\\s*,/  AND \"query\" !~ /\\/\\*\\s*pgwatch2_generated\\s*\\*\\// GROUP BY time(3650d), \"queryid\", \"query\" fill(none) )  where $timeFilter AND c > 0 group by time(3650d),  \"queryid\", \"query\" )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top queries by calls",
   "type": "table",
   "description": "NB! If there has been a pg_stat_statement reset or a server crash in the selected timerange, the information is false",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "ass",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"spread\", \"queryid\", \"query\", $top) FROM (SELECT spread(\"calls\") FROM \"stat_statements\" WHERE $timeFilter AND \"dbname\" = '$dbname' AND \"query\" !~ /extract.*::int8\\s+as\\s+epoch_ns\\s*,/  AND \"query\" !~ /\\/\\*\\s*pgwatch2_generated\\s*\\*\\// GROUP BY time(3650d), \"queryid\", \"query\" fill(none) ) WHERE spread > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top queries by IO",
   "type": "table",
   "description": "NB! If there has been a pg_stat_statement reset or a server crash in the selected timerange, the information is false",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"spread\", \"queryid\", \"query\", $top) FROM (SELECT spread(\"blk_read_time\") + spread(\"blk_write_time\") AS spread FROM \"stat_statements\" WHERE $timeFilter AND \"dbname\" = '$dbname' AND \"query\" !~ /extract.*::int8\\s+as\\s+epoch_ns\\s*,/  AND \"query\" !~ /\\/\\*\\s*pgwatch2_generated\\s*\\*\\// GROUP BY time(3650d), \"queryid\", \"query\" fill(none) ) WHERE spread > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2020/11/CYBERTEC_RGB_300x80px.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}