{
 "title": "Change events",
 "description": "use change_events metric for capturing table/index/sproc/postgresql.conf changes",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics ORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "DDL / config change events",
   "type": "graph",
   "description": "If there are no vertical red stripes then no changes were detected for that time period",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  avg((data->'load_5min')::float8) as \"load_5min\"\nFROM\n  cpu_load\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nGROUP BY 1\nORDER BY 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "Rollback ratio",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg( case when (xc = xc_lag and xr = xr_lag) then null else ( ((xr - xr_lag)::numeric*100) / ((xc - xc_lag) + (xr - xr_lag)) ) end ) as \"Rollback ratio\"\nfrom (\n  select\n    (data->'xact_rollback')::float8 as xr, lag((data->'xact_rollback')::float8) over w as xr_lag,\n    (data->'xact_commit')::float8 as xc, lag((data->'xact_rollback')::float8) over w as xc_lag,\n    time\n  from db_stats\n    where dbname = '$dbname'\n    and $__timeFilter(time)\n  window w as (order by time)\n) x\nwhere xc >= xc_lag\ngroup by 1\norder by 1\n\n\n\n\n\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Table changes",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "object_changes",
     "rawSql": "SELECT\n  (date_trunc('minute', time))::text as time,\n  data->>'event' as event,\n  tag_data->>'table' as table\nFROM\n  table_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Index changes",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "object_changes",
     "rawSql": "SELECT\n  (date_trunc('minute', time))::text as time,\n  data->>'event' as event,\n  tag_data->>'index' as index,\n  data->>'table' as table\nFROM\n  index_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Sproc changes",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  time::text,\n  data->>'event' as event,\n  tag_data->>'sproc' as sproc\nFROM\n  sproc_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Config changes",
   "type": "table",
   "description": "postgresql.conf settings changes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  time::text,\n  tag_data->>'setting' as event,\n  data->>'value' as value\nFROM\n  configuration_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Login and superuser role changes",
   "type": "table-old",
   "description": "Instance level",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  (date_trunc('minute', time))::text as time,\n  tag_data->>'role' as role,\n  data->>'event' as event,  \n  data->>'privilege_type' as privilege_type\nFROM\n  privilege_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\n  AND (data->>'privilege_type' = 'LOGIN'\n    OR data->>'privilege_type' = 'SUPERUSER') \nORDER BY\n  time, tag_data->>'role', data->>'privilege_type'"
    }
   ]
  },
  {
   "title": "Privilege changes",
   "type": "table-old",
   "description": "Per database",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  (date_trunc('minute', time))::text as time,\n  tag_data->>'role' as role,\n  data->>'event' as event,  \n  data->>'privilege_type' as privilege_type,\n  tag_data->>'object' as object\nFROM\n  privilege_changes\nWHERE\n  $__timeFilter(time)\n  AND dbname = '$dbname'\n  AND data->>'privilege_type' != 'LOGIN'\n  AND data->>'privilege_type' != 'SUPERUSER'\nORDER BY\n  time, tag_data->>'role', data->>'privilege_type', data->>'object'"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select\n  (select time from settings where $__timeFilter(time) order by time desc limit 1) as \"Time\",\n  key,\n  value::text as value\nfrom (\n  select * from jsonb_each((select data from settings where $__timeFilter(time) order by time desc limit 1))\n) x;"
    }
   ]
  }
 ]
}