{
 "title": "Biggest relations treemap",
 "description": "Depends on the \"Heatmap\" plugin. Based on latest \"table/index_stats\" data",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES WITH KEY = \"dbname\""
   }
  ]
 },
 "panels": [
  {
   "title": "Biggest by total relation size",
   "type": "savantly-heatmap-panel",
   "description": "NB! Depends on the \"Heatmap\" plugin.\nFYI - shown sizes are in MB i.e. 10^6, Postgres 'psql' client reports them in MiB (1048576 B)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "targets": [
    {
     "alias": "$tag_table_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"total_relation_size_b\")  as value FROM \"table_stats\" WHERE \"dbname\" = '$dbname' AND time > now() - 1h GROUP BY time(15m), \"table_name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Biggest tables (w/o indexes)",
   "type": "savantly-heatmap-panel",
   "description": "NB! Depends on the \"Heatmap\" plugin.\nFYI - shown sizes are in MB i.e. 10^6, Postgres 'psql' client reports them in MiB (1048576 B)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "format": "none",
   "targets": [
    {
     "alias": "$tag_table_name",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "table_full_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "SELECT last(\"table_size_b\")  as value FROM \"table_stats\" WHERE \"dbname\" = '$dbname' AND time > now() - 1h GROUP BY time(15m), \"table_name\" fill(0)",
     "select": [
      [
       { "params": [ "total_relation_size_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=", "value": "$dbname" }
     ]
    }
   ]
  },
  {
   "title": "Biggest indexes",
   "type": "savantly-heatmap-panel",
   "description": "NB! Depends on the \"Heatmap\" plugin.\nFYI - shown sizes are in MB i.e. 10^6, Postgres 'psql' client reports them in MiB (1048576 B)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "format": "none",
   "targets": [
    {
     "alias": "$tag_index_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"index_size_b\")  as value FROM \"index_stats\" WHERE (\"dbname\" = '$dbname') AND time > now() - 1h GROUP BY time(15m), \"index_name\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2017/11/Cybertec_Logo_2017_300px_slogan_trans.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}