{
 "title": "DB overview",
 "tags": [ "pgwatch2" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES WITH KEY = \"dbname\" "
   },
   {
    "name": "agg_interval",
    "query": "1s,1m,5m,10m,15m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance state",
   "type": "singlestat",
   "description": "Last 5min data",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"in_recovery_int\") FROM \"wal\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(365d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instance uptime",
   "type": "singlestat",
   "description": "Last 5min data",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "db_stats",
     "select": [
      [
       { "params": [ "postmaster_uptime_s" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "TPS",
   "type": "singlestat",
   "description": "Current Transaction Per Second + last 6h history",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"xact_commit\"), 1s) + non_negative_derivative(last(\"xact_rollback\"), 1s) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "description": "Current Queries Per Second (>5min avg) + last 6h history",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"calls\"), 1s) FROM \"stat_statements_calls\" WHERE $timeFilter AND \"dbname\" =~ /^$dbname$/ GROUP BY time(10m) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query runtime",
   "type": "singlestat",
   "description": "Current (5min+ avg) query runtime + last 6h history. Requires pg_stat_statements extension and the \"get_stat_statements\" helper function  from  the \"sql/metric_fetching_helpers\" folder on the monitored DB",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "avg_query_runtime_per_db",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(q) from (SELECT non_negative_derivative(mean(\"total_time\")) / non_negative_derivative(mean(\"calls\")) as q FROM \"stat_statements\" WHERE \"dbname\" =~ /^$dbname$/ AND \"query\" !~ /(?i)::int8[\\s+]as[\\s]+epoch_ns/ AND $timeFilter GROUP BY queryid, time($__interval) fill(none)) group by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB size ch. 1h",
   "type": "singlestat",
   "description": "For last hour + 6h history",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "db_size_change_last_hour",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"size_b\")  - first(\"size_b\") FROM \"db_size\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Approx Table Bloat",
   "type": "singlestat",
   "description": "Based on a pure SQL  based estimate for fast results. Needs \"get_table_bloat_approx_sql\" helper. Re-check with \"pgstattuple\" if numbers look suspicious!",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Bloat size",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_bloat_approx_summary",
     "query": "SELECT mean(\"approx_table_bloat_b\" ) FROM \"table_bloat_approx_summary_sql\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "approx_free_space_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Tuples fetched vs returned",
   "type": "singlestat",
   "description": "Percentage of rows touched by queries that are actually returned to the client. Low numbers (< 10%) for an OLTP workload can hint at missing indexes",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT  non_negative_derivative(mean(\"tup_fetched\")) / non_negative_derivative(mean(\"tup_returned\")) * 100 FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Tuple  ins. / upd. / del. statistics ($agg_interval avg. rate., log. scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "DELETE",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(mean(\"tup_deleted\"), $agg_interval) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "tup_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "UPDATE",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tup_updated\"), $agg_interval) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "INSERT",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"tup_inserted\"), $agg_interval) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers hit ratio + Rollback ratio ($agg_interval avg.)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Shared buffers hit ratio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT ( non_negative_derivative(mean(\"blks_hit\")) / (non_negative_derivative(mean(\"blks_hit\")) + non_negative_derivative(mean(\"blks_read\")))) * 100 FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TX rollback ratio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (non_negative_derivative(mean(\"xact_rollback\")) / (non_negative_derivative(mean(\"xact_commit\")) + non_negative_derivative(mean(\"xact_rollback\"))) * 100) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TPS / QPS",
   "type": "graph",
   "description": "Transactions per Second / Queries per Second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"xact_commit\"), 1s) + non_negative_derivative(last(\"xact_rollback\"), 1s) FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "numbackends" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "query": "SELECT non_negative_derivative(last(\"calls\"), 1s) FROM \"stat_statements_calls\" WHERE $timeFilter AND \"dbname\" =~ /^$dbname$/ GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAL rate + DB size ($agg_interval avg.)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "WAL rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wal",
     "query": "SELECT derivative(mean(\"xlog_location_b\"), 1s) FROM \"wal\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "xlog_location_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "DB Size",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "db_size",
     "select": [
      [
       { "params": [ "size_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Sessions by state ($agg_interval avg.)",
   "type": "graph",
   "description": "Assumes get_stat_activity() helper for unprivileged monitoring roles",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT mean(\"idle\") FROM \"backends\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "idle in transaction",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "select": [
      [
       { "params": [ "idleintransaction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "waiting",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "select": [
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    },
    {
     "alias": "av_workers",
     "groupBy": [
      { "params": [ "$agg_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "backends",
     "select": [
      [
       { "params": [ "av_workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU load + avg. query runtime ($agg_interval avg.)",
   "type": "graph",
   "description": "Requires according \"metric fetching helpers\" on the monitored server",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "load_5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT mean(\"load_5min\") FROM \"cpu_load\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "avg_query_runtime",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "select mean(runtime) from (SELECT non_negative_derivative(last(\"total_time\"), 1h) / non_negative_derivative(last(\"calls\"), 1h) as runtime FROM \"stat_statements\" WHERE \"dbname\" =~ /^$dbname$/ AND \"query\" !~ /(?i)::int8[\\s]+as[\\s]+epoch_ns/ AND $timeFilter GROUP BY queryid, time($agg_interval) fill(none)) group by time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seq. / Idx. scans ($agg_interval avg., >10MB tables, log. scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "select sum(seq_scan) as seq_scan,  sum(idx_scan) as idx_scan from (SELECT non_negative_derivative(mean(\"seq_scan\"), $agg_interval) as seq_scan, non_negative_derivative(mean(\"idx_scan\"), $agg_interval) as idx_scan FROM \"table_stats\" WHERE (\"dbname\" =~ /^$dbname$/) AND $timeFilter AND table_size_b > 10000000 GROUP BY time($agg_interval), table_full_name fill(none)) GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp bytes ($agg_interval avg.)",
   "type": "graph",
   "description": "Appears when larger groupings / sortings don't fit into 'work_mem'",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT mean(temp_bytes) as temp_bytes FROM (SELECT non_negative_derivative(\"temp_bytes\", $agg_interval) as temp_bytes FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter) GROUP BY time($agg_interval) fill(none)",
     "select": [
      [
       { "params": [ "load_5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2020/11/CYBERTEC_RGB_300x80px.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}