{
 "title": "Recommendations",
 "description": "Needs \"recommendations\" metric to be enabled",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SHOW TAG VALUES FROM \"recommendations\" WITH KEY = \"dbname\""
   }
  ]
 },
 "panels": [
  {
   "title": "Overusage of SUPERUSER",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  -- last(\"major_ver\") as pg_major_ver,\n  last(\"recommendation\") as recommendation,\n  last(\"extra_info\") as extra_info\nFROM\n  \"recommendations\"\nWHERE\n  $timeFilter\n  AND dbname =~ /^$dbname$/\n  AND reco_topic = 'superuser_count'\nGROUP BY time(365d), dbname, reco_topic, object_name fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SECURITY DEFINER without fixed \"search_path\"",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  last(\"recommendation\") as recommendation,\n  last(\"extra_info\") as extra_info\nFROM\n  \"recommendations\"\nWHERE\n  $timeFilter\n  AND dbname =~ /^$dbname$/\n  AND reco_topic = 'sprocs_wo_search_path'\nGROUP BY time(365d), dbname, reco_topic, object_name fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUBLIC schemas with default privileges",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  last(\"recommendation\") as recommendation,\n  last(\"extra_info\") as extra_info\nFROM\n  \"recommendations\"\nWHERE\n  $timeFilter\n  AND dbname =~ /^$dbname$/\n  AND reco_topic = 'default_public_schema_privs'\nGROUP BY time(365d), dbname, reco_topic, object_name fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Possibly missing indexes",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  last(\"recommendation\") as recommendation,\n  last(\"extra_info\") as extra_info\nFROM\n  \"recommendations\"\nWHERE\n  $timeFilter\n  AND dbname =~ /^$dbname$/\n  AND reco_topic = 'create_index'\nGROUP BY time(365d), dbname, reco_topic, object_name fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unused indexes",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  last(\"recommendation\") as recommendation,\n  last(\"extra_info\") as extra_info\nFROM\n  \"recommendations\"\nWHERE\n  $timeFilter\n  AND dbname =~ /^$dbname$/\n  AND reco_topic = 'drop_index'\nGROUP BY time(365d), dbname, reco_topic, object_name fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Partial index suggestions",
   "type": "table",
   "description": "A lot of space / performance can be won on replacing columns that contain mostly NULL-s but are  fully indexed with partial indexes, leaving out NULL-s",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  last(\"recommendation\") as recommendation,\n  last(\"extra_info\") as extra_info\nFROM\n  \"recommendations\"\nWHERE\n  $timeFilter\n  AND dbname =~ /^$dbname$/\n  AND reco_topic = 'partial_index_candidates'\nGROUP BY time(365d), dbname, reco_topic, object_name fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deeply nested views",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  last(\"major_ver\") as pg_major_ver,\n  last(\"recommendation\") as recommendation,\n  last(\"extra_info\") as extra_info\nFROM\n  \"recommendations\"\nWHERE\n  $timeFilter\n  AND dbname =~ /^$dbname$/\n  AND reco_topic = 'overly_nested_views'\nGROUP BY time(365d), dbname, reco_topic, object_name fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}