apiVersion: v1
kind: Template
metadata:
  name: pgwatch2-template 
objects:
- kind: "DeploymentConfig"
  apiVersion: v1
  metadata:
    name: "pgwatch2"
  spec:
    template:
      metadata:
        labels:
          name: "pgwatch2"
      spec:
        containers:
          - name: "pgwatch2"
            image: "cybertec/pgwatch2-nonroot"
            ports:
              - containerPort: 8080
                protocol: "TCP"
              - containerPort: 3000
                protocol: "TCP"
              - containerPort: 5432
                protocol: "TCP"
              - containerPort: 8086
                protocol: "TCP"
              - containerPort: 8088
                protocol: "TCP"
            volumeMounts:
              - mountPath: /pgwatch2/persistent-config
                name: pgwatch2-config
              - mountPath: /var/lib/postgresql
                name: pgwatch2-postgresql
              - mountPath: /var/lib/grafana
                name: pgwatch2-grafana
              - mountPath: /var/lib/influxdb
                name: pgwatch2-influx
            livenessProbe:
              exec:
                command:
                - /usr/bin/pg_isready
                - -qU
                - pgwatch2
              initialDelaySeconds: 30
              periodSeconds: 30
            env:
              - name: NOTESTDB
                value: ${NOTESTDB}
              - name: PW2_GRAFANASSL
                value: ${PW2_GRAFANASSL}
              - name: PW2_WEBSSL
                value: ${PW2_WEBSSL}
              - name: PW2_WEBNOANONYMOUS
                value: ${PW2_WEBNOANONYMOUS}
              - name: PW2_WEBUSER
                value: ${PW2_WEBUSER}
              - name: PW2_WEBPASSWORD
                value: ${PW2_WEBPASSWORD}
              - name: PW2_GRAFANA_BASEURL
                value: ${PW2_GRAFANA_BASEURL}
              - name: PW2_PGHOST
                value: ${PW2_PGHOST}
              - name: PW2_PGPORT
                value: ${PW2_PGPORT}
              - name: PW2_PGDATABASE
                value: ${PW2_PGDATABASE}
              - name: PW2_PGUSER
                value: ${PW2_PGUSER}
              - name: PW2_PGPASSWORD
                value: ${PW2_PGPASSWORD}
              - name: PW2_PGSSL
                value: ${PW2_PGSSL}
              - name: PW2_IHOST
                value: ${PW2_IHOST}
              - name: PW2_IPORT
                value: ${PW2_IPORT}
              - name: PW2_IDATABASE
                value: ${PW2_IDATABASE}
              - name: PW2_IUSER
                value: ${PW2_IUSER}
              - name: PW2_IPASSWORD
                value: ${PW2_IPASSWORD}
              - name: PW2_ISSL
                value: ${PW2_ISSL}
              - name: PW2_IRETENTIONDAYS
                value: ${PW2_IRETENTIONDAYS}
              - name: PW2_DATASTORE
                value: ${PW2_DATASTORE}
              - name: PW2_GRAPHITEHOST
                value: ${PW2_GRAPHITEHOST}
              - name: PW2_GRAPHITEPORT
                value: ${PW2_GRAPHITEPORT}
        volumes:
        - name: pgwatch2-config
          persistentVolumeClaim:
            claimName: ${PVC_PGWATCH2}
        - name: pgwatch2-postgresql
          persistentVolumeClaim:
            claimName: ${PVC_POSTGRESQL}
        - name: pgwatch2-grafana
          persistentVolumeClaim:
            claimName: ${PVC_GRAFANA}
        - name: pgwatch2-influx
          persistentVolumeClaim:
            claimName: ${PVC_INFLUX}
    replicas: 1
    strategy:
      type: "Recreate"
    paused: false
    revisionHistoryLimit: 3
    minReadySeconds: 0
- kind: Service
  apiVersion: v1
  metadata:
    name: pgwatch2-webui
  spec:
    selector:
      name: pgwatch2
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
- kind: Service
  apiVersion: v1
  metadata:
    name: pgwatch2-grafana
  spec:
    selector:
      name: pgwatch2
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
parameters:
- description: PVC name for pgwatch2 config(must be pre-created, min 10 MB)
  name: PVC_PGWATCH2
  value: ""
  required: true
- description: PVC name for Postgres (must be pre-created, min 100 MB)
  name: PVC_POSTGRESQL
  value: ""
  required: true
- description: PVC name for Grafana (must be pre-created, min 10MB, needed only when installing plugins)
  name: PVC_GRAFANA
  value: ""
  required: true
- description: PVC name for InfluxDB (must be pre-created, min 1 GB, ~250 MB per monitored instance per month in "exhaustive" settings)
  name: PVC_INFLUX
  value: ""
  required: true
- description: Don't add the local config DB to monitoring
  name: NOTESTDB
  value: ""
- description: Use self signed SSL for Grafana
  name: PW2_GRAFANASSL
  value: ""
- description: Use self signed SSL for the Admin UI
  name: PW2_WEBSSL
  value: ""
- description: Passoword protect config changes via the Web UI. Disabled by default
  name: PW2_WEBNOANONYMOUS
  value: ""
- description: Web UI admin user
  name: PW2_WEBUSER
  value: "admin"
- description: Web UI admin user password
  name: PW2_WEBPASSWORD
  value: "pgwatch2admin"
- description: Can be set to require login even for viewing dashboards
  name: PW2_GRAFANANOANONYMOUS
  value: ""
- description: Grafana administrative user
  name: PW2_GRAFANAUSER
  value: "admin"
- description: Grafana administrative user password
  name: PW2_GRAFANAPASSWORD
  value: "pgwatch2admin"
- description: When using Grafana externally, set this to get correct links from the Admin UI
  name: PW2_GRAFANA_BASEURL
  value: ""
- description: Postgres config store (internal DB used by default, adjust following 5 params for an external DB)
  name: PW2_PGHOST
  value: "localhost"
- description: Use an external Postgres DB as config store instead of the internal one
  name: PW2_PGPORT
  value: "5432"
- description: Postgres config store - DB name
  name: PW2_PGDATABASE
  value: "pgwatch2"
- description: Postgres config store - user
  name: PW2_PGUSER
  value: "pgwatch2"
- description: Postgres config store - password
  name: PW2_PGPASSWORD
  value: ""
- description: Postgres config store - require SSL
  name: PW2_PGSSL
  value: ""
- description: Use already External Influx DB for storing metrics
  name: PW2_IHOST
  value: "localhost"
- description: External Influx DB - port
  name: PW2_IPORT
  value: "8086"
- description: External Influx DB - DB name
  name: PW2_IDATABASE
  value: "pgwatch2"
- description: External Influx DB - user
  name: PW2_IUSER
  value: "root"
- description: External Influx DB - password
  name: PW2_IPASSWORD
  value: "root"
- description: External Influx DB - require SSL
  name: PW2_ISSL
  value: "false"
- description: Influx DB metrics retention period in days
  name: PW2_IRETENTIONDAYS
  value: "90"
- description: Set to "graphite" to use external Graphite server as metrics datastore
  name: PW2_DATASTORE
  value: "influx"
- description: External Graphite - host
  name: PW2_GRAPHITEHOST
  value: ""
- description: External Graphite - port
  name: PW2_GRAPHITEPORT
  value: ""
