name: Update Docker
on: 
  push:
    # paths:
    #   - '**.go'
    #   - '**.yaml'
    #   - '**.yml'
    #   - 'go.mod'
    #   - 'go.sum'
    #   - 'Dockerfile'  
    branches:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*      
  workflow_dispatch:

jobs:
  docker:
    if: true # false to skip job during debug
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - id: version
      name: version
      run: |
        echo "::set-output name=RELEASE_VERSION::$(echo $GITHUB_REF_NAME_${GITHUB_SHA:6})
        echo "::set-output name=RELEASE_TIME::$(git show -s --format=%cI HEAD)
    # - name: Set up Golang
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: '1.16'

    # despite the fact docker will build binary internally 
    # we want to stop workflow in case of any error before pushing to registry 
    - name: Get dependencies and Build
      env:
        GIT_HASH: ${{ steps.version.outputs.RELEASE_VERSION }}
        GIT_TIME: ${{ steps.version.outputs.RELEASE_TIME }}
      run: |
          echo "$GIT_HASH and $GIT_TIME"

    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   env:
    #     GIT_HASH: ${{ env.STATE_RELEASE_VERSION }}
    #     GIT_TIME: ${{ env.STATE_RELEASE_TIME }}      
    #   with:
    #     name: cybertec/pgwatch2-postgres
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     dockerfile: docker/Dockerfile-postgres
    #     buildargs: GIT_HASH,GIT_TIME
    #     tags: "gha_test"
    #     tag_semver: true
